name: tinnsleep-env
dependencies:
    # mandatory dependencies
    - python>=3.7
    - numpy>=1.16.4
    - pytest>=4.0.2
    - scikit-learn>=0.22.1
    - pandas
    - scipy
    - matplotlib
    - seaborn

    # jupyter lab dependencies (optional)
    - jupyter
    - jupyterlab
    - ipympl            # for widget visualization
    - ipykernel         # for managing jupyter kernel
    - nodejs            # for widget visualization

    # test dependencies (optional)
    - coverage
    - pytest

    # Pip dependencies
    - pip
    - pip:
        # mandatory dependencies
        - mne