# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches: 
      - '*'

jobs:

  build:
    name: miniconda-Linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1.0.2
        with:
           activate-environment: tinnsleep-env
           environment-file: environment.yaml
           python-version: 3.7
           auto-activate-base: true
           auto_update_conda: true
      - shell: bash -l {0}
        name: condalist
        run: |
          conda info
          conda list

