# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches: 
      - '*'

jobs:

  build:
    name: miniconda-Linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: tinnsleep-env
           environment-file: environment.yaml
           python-version: 3.7
           auto-activate-base: true
           auto_update_conda: true
      - shell: bash -l {0}
        name: condalist
        run: |
          conda info
          conda list

  pytest:
    name: miniconda-pytest
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: tinnsleep-env
           environment-file: environment.yaml
           python-version: 3.7
           auto-activate-base: true
           auto_update_conda: true
      - name: Git indentification settings
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Pytest and Coverage
        run: |
          chmod u+r+x ./gitcommit2.sh
          ./gitcommit2.sh -m "update coverage"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}